### ISSUE TITLE
Should be able to search over websocket

### ISSUE THREAD

**Issue by megatrond** [jgilje/reveller#1]
{"action":"find","argument":[searchterm]}

return:

{"type":"find", "data":"[escaped array of results (because)]"}

one result: 

{"type": ["d"|"f"], "path":"path to containing directory", "name":"name of directory or file"}

**Comment by toblix** [comment]
This would be useful

**Comment by jgilje** [comment]
Action implemented, searchstring in argument, ex.
{"action": "search", "argument": "Monty"}

Case sensitive for now
