### ISSUE TITLE
When SID chip is powered off 5v & 12v rail should be turned off

### ISSUE THREAD

**Issue by tmolbergen** [jgilje/reveller#6]
Review how to cut 5v and 12v from sid chip when reveller is exited.

**Comment by jgilje** [comment]
nais! you know what to do :)

**Comment by tmolberg** [comment]
After reviewing boarddesign it looks like 5v and 12v is cut. Closing this for now...

**Comment by jgilje** [comment]
I'm 97% sure the 5V is always on

**Comment by jgilje** [comment]
good news (tm). 5V is cut
