### ISSUE TITLE
Create install shell script

### ISSUE THREAD

**Issue by tmolberg** [jgilje/reveller#8]
Install script should download necessary packages and compile & move binarys to respective locations. 
Remember to include rpi kernel driver. 
Include optional for downloading latest sid music? 

I.E 
sidplayer to /opt/ ? 
sidplayer web backend to /opt/ ?
sidplayer web frontend to /var/www  ?

**Comment by tmolberg** [comment]
according to @jgilje this can be resolved with cmake -> investigate possibilities.

**Comment by jgilje** [comment]
need a way to get the reveller systemd unit to load the kernel driver. the other parts are done here.

**Comment by tmolbergen** [comment]
kernel modules are being loaded using systemd kernel modules loader via modules-conf.d/reveller (which causes systemd to load the module on boot) 

bc65fd8bd7096a922209b9d8947569593142da3d
